"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!*ps4ta(fhli=jzd2wx^4wfw82q40xjui3vk08o9nit68k@pv1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    
    # All Services
    'customer_service',
    'guest_customer_service',
    'register_customer_service',
    'vip_customer_service',
    'items_service',
    'book_service',
    'laptop_service',
    'mobile_service',
    'clothes_service',
    'cart_service',
    'order_service',
    'paying_service',
    'shipping_service',
    'gateway_service',
    'rating_service',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'items_filters': 'items_service.templatetags.items_filters',
            }
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'guest_customers': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'guest_customers.sqlite3',
    },
    'registered_customers': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ecommerce_register_customers',
        'USER': 'root',
        'PASSWORD': '2512',
        'HOST': 'localhost',
        'PORT': '3306',
    },
    'vip_customers': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ecommerce_vip_customers',
        'USER': 'root',
        'PASSWORD': '2512',
        'HOST': 'localhost',
        'PORT': '3306',
    },
    'books': {
        'ENGINE': 'djongo',
        'NAME': 'ecommerce_books',
        'ENFORCE_SCHEMA': False,
        'HOST': 'localhost',
        'PORT': 27017
    },
    'laptops': {
        'ENGINE': 'djongo',
        'NAME': 'ecommerce_laptops',
        'ENFORCE_SCHEMA': False,
        'HOST': 'localhost',
        'PORT': 27017
    },
    'mobiles': {
        'ENGINE': 'djongo',
        'NAME': 'ecommerce_mobiles',
        'ENFORCE_SCHEMA': False,
        'HOST': 'localhost',
        'PORT': 27017
    },
    'clothes': {
        'ENGINE': 'djongo',
        'NAME': 'ecommerce_clothes',
        'ENFORCE_SCHEMA': False,
        'HOST': 'localhost',
        'PORT': 27017
    },
    'items': {
        'ENGINE': 'djongo',
        'NAME': 'ecommerce_items',
        'ENFORCE_SCHEMA': False,
        'HOST': 'localhost',
        'PORT': 27017
    },
    'transactions': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ecommerce_transactions',
        'USER': 'postgres',
        'PASSWORD': '2512',
        'HOST': 'localhost',
        'PORT': '5432',
    },
}

# Database router
DATABASE_ROUTERS = ['ecommerce.database_router.DatabaseRouter']


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}

# Service URLs
SERVICE_URLS = {
    # Customer services
    'customers': 'http://localhost:8000/api/customers/',
    'guest-customers': 'http://localhost:8000/api/guest-customers/',
    'registered-customers': 'http://localhost:8000/api/registered-customers/',
    'vip-customers': 'http://localhost:8000/api/vip-customers/',
    
    # Item services
    'items': 'http://localhost:8000/api/items/',
    'books': 'http://localhost:8000/api/books/',
    'laptops': 'http://localhost:8000/api/laptops/',
    'mobiles': 'http://localhost:8000/api/mobiles/',
    'clothes': 'http://localhost:8000/api/clothes/',
    
    # Transaction services
    'carts': 'http://localhost:8000/api/carts/',
    'orders': 'http://localhost:8000/api/orders/',
    'payments': 'http://localhost:8000/api/payments/',
    'shipping': 'http://localhost:8000/api/shipping/',
    
    # Rating service
    'ratings': 'http://localhost:8000/api/ratings/',
}
