# Generated by Django 3.2.18 on 2025-04-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex'), ('children', 'Children')], max_length=20)),
                ('category', models.CharField(choices=[('tops', 'Tops'), ('shirts', 'Shirts'), ('tshirts', 'T-Shirts'), ('dresses', 'Dresses'), ('pants', 'Pants'), ('jeans', 'Jeans'), ('shorts', 'Shorts'), ('skirts', 'Skirts'), ('jackets', 'Jackets'), ('coats', 'Coats'), ('sweaters', 'Sweaters'), ('hoodies', 'Hoodies'), ('activewear', 'Activewear'), ('swimwear', 'Swimwear'), ('lingerie', 'Lingerie'), ('sleepwear', 'Sleepwear'), ('suits', 'Suits'), ('socks', 'Socks'), ('underwear', 'Underwear'), ('accessories', 'Accessories'), ('other', 'Other')], max_length=50)),
                ('size_system', models.CharField(choices=[('us', 'US'), ('eu', 'EU'), ('uk', 'UK'), ('intl', 'International')], default='us', max_length=10)),
                ('available_sizes', models.JSONField(help_text="e.g., ['S', 'M', 'L', 'XL']")),
                ('material', models.CharField(help_text='Primary material, e.g., Cotton, Polyester', max_length=255)),
                ('composition', models.JSONField(help_text="e.g., {'cotton': 80, 'polyester': 20} for 80% cotton, 20% polyester")),
                ('style', models.CharField(blank=True, max_length=100)),
                ('fit', models.CharField(blank=True, help_text='e.g., Regular, Slim, Loose, Oversize', max_length=50)),
                ('season', models.CharField(blank=True, help_text='e.g., Summer, Winter, All Seasons', max_length=50)),
                ('primary_color', models.CharField(max_length=50)),
                ('secondary_color', models.CharField(blank=True, max_length=50)),
                ('color_variants', models.JSONField(default=list, help_text='List of available color options')),
                ('pattern', models.CharField(blank=True, help_text='e.g., Solid, Striped, Plaid, Floral', max_length=50)),
                ('care_instructions', models.TextField(blank=True)),
                ('wash_type', models.CharField(blank=True, help_text='e.g., Machine wash, Hand wash, Dry clean', max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in grams', max_digits=5, null=True)),
                ('origin', models.CharField(blank=True, help_text='Country/region of origin', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('stock_quantity', models.JSONField(help_text="Stock by size and color, e.g., {'S:Red': 10, 'M:Red': 5}")),
                ('sku', models.CharField(help_text='Stock Keeping Unit', max_length=100, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image_url', models.URLField()),
                ('additional_images', models.JSONField(default=list, help_text='List of additional image URLs')),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list, help_text='List of product features')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='clothes',
            index=models.Index(fields=['name'], name='clothes_ser_name_22f1a5_idx'),
        ),
        migrations.AddIndex(
            model_name='clothes',
            index=models.Index(fields=['brand'], name='clothes_ser_brand_f2feb0_idx'),
        ),
        migrations.AddIndex(
            model_name='clothes',
            index=models.Index(fields=['gender'], name='clothes_ser_gender_519fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='clothes',
            index=models.Index(fields=['category'], name='clothes_ser_categor_0128e1_idx'),
        ),
        migrations.AddIndex(
            model_name='clothes',
            index=models.Index(fields=['price'], name='clothes_ser_price_42f324_idx'),
        ),
        migrations.AddIndex(
            model_name='clothes',
            index=models.Index(fields=['primary_color'], name='clothes_ser_primary_a9e5be_idx'),
        ),
    ]
