# Generated by Django 3.2.18 on 2025-04-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('expandable_storage', models.BooleanField(default=False)),
                ('max_expandable_storage', models.IntegerField(blank=True, null=True)),
                ('screen_size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('resolution', models.CharField(max_length=50)),
                ('display_type', models.CharField(max_length=50)),
                ('refresh_rate', models.IntegerField(default=60)),
                ('rear_cameras', models.JSONField()),
                ('front_cameras', models.JSONField()),
                ('video_recording', models.CharField(max_length=50)),
                ('battery_capacity', models.IntegerField()),
                ('fast_charging', models.BooleanField(default=False)),
                ('wireless_charging', models.BooleanField(default=False)),
                ('network_type', models.CharField(choices=[('2g', '2G'), ('3g', '3G'), ('4g', '4G'), ('5g', '5G')], max_length=10)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_bluetooth', models.BooleanField(default=True)),
                ('has_nfc', models.BooleanField(default=False)),
                ('has_infrared', models.BooleanField(default=False)),
                ('dimensions', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=5)),
                ('water_resistance_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('operating_system', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('windows', 'Windows'), ('other', 'Other')], max_length=50)),
                ('os_version', models.CharField(max_length=50)),
                ('fingerprint_sensor', models.BooleanField(default=False)),
                ('face_recognition', models.BooleanField(default=False)),
                ('stereo_speakers', models.BooleanField(default=False)),
                ('headphone_jack', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField()),
                ('image_url', models.URLField()),
                ('is_available', models.BooleanField(default=True)),
                ('warranty_period', models.IntegerField()),
                ('color_variants', models.JSONField()),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='mobile',
            index=models.Index(fields=['name'], name='mobile_serv_name_1fe4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='mobile',
            index=models.Index(fields=['brand'], name='mobile_serv_brand_c121e3_idx'),
        ),
        migrations.AddIndex(
            model_name='mobile',
            index=models.Index(fields=['price'], name='mobile_serv_price_91c718_idx'),
        ),
        migrations.AddIndex(
            model_name='mobile',
            index=models.Index(fields=['ram'], name='mobile_serv_ram_32909b_idx'),
        ),
        migrations.AddIndex(
            model_name='mobile',
            index=models.Index(fields=['storage'], name='mobile_serv_storage_aa2505_idx'),
        ),
        migrations.AddIndex(
            model_name='mobile',
            index=models.Index(fields=['network_type'], name='mobile_serv_network_bc0431_idx'),
        ),
    ]
